builds:
  hero:
    AR:
      AR_EC: "energy_compression:1/power_surge:1/perfected_form:1/resonant_energy:1/manifested_power:1/word_of_supremacy:1/shock_pulse:1/word_of_supremacy:1/empowered_surges:1/concentrated_infusion:1/energy_cycle:1/divine_halo:1"
      AR_SP: "sustained_potency:1/power_surge:1/perfected_form:1/resonant_energy:1/manifested_power:1/word_of_supremacy:1/shock_pulse:1/word_of_supremacy:1/empowered_surges:1/concentrated_infusion:1/energy_cycle:1/divine_halo:1"
    # Darkening Horizon is currently bugged, need to hard code 125982 for the ID
    VW:
      VW_VE_DoS: "void_empowerment:1/depth_of_shadows:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
      VW_DH_DoS: "125982:1/depth_of_shadows:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
      VW_VE_VW: "void_empowerment:1/voidwraith:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
      VW_DH_VW: "125982:1/voidwraith:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
  # add here as well if you ever change this https://github.com/Bloodmallet/bloodytools/blob/master/bloodytools/simulations/talent_tree_paths/priest_shadow.yaml
  vw-da-cthun-dr:
    gearSetup: default
    talents:
      composite:
        name: VW_DH_VW_DA_yshaarj_cthun_81151017351087_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYGDAAAAAAAAAAAAwMmtxYmZWGMzMmtZwgZhZmxY2YgxYYWMbTNzgFYmZGAUAmtZbJY2YD
      dungeons:
        name: VW_DH_VW_DA_nzoth_cthun_98245820544943_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMwMzAAAAAAAAAAAAAwYs5BGzMzy4BMzMmtZwgZhZmxY2YgxYYWMbTNzgFYmZGAUAmtZbJY2YD
      single:
        name: VW_DH_VW_DA_yshaarj_cthun_81151051920303_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwwYAAAAAAAAAAAAAmZmtxYmZWGMzMGzgBzCzMjxsxAjxwsY2mamBLwMzMAoAMbz2SwsxG
      2t:
        name: VW_DH_VW_DA_yshaarj_cthun_81151086286767_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYGDAAAAAAAAAAAAwMsNGzMzCjZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      3t:
        name: VW_DH_VW_DA_nzoth_cthun_98193585723311_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMwYmZAAAAAAAAAAAAAmhtxYmZWgZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      4t:
        name: VW_DH_VW_DA_nzoth_cthun_98193585723311_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMwYmZAAAAAAAAAAAAAmhtxYmZWgZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
  ar-cthun:
    gearSetup: default
    talents:
      composite:
        name: AR_SP_VF_yogg_cthun_119173496149935_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAgBzMDAAAAAAAAAAAAwwswYmZ2YMzMzsNwgZjZmxY2YgxYYWMbTNzgFMDgZ2sM1sYAIjxCA
      dungeons:
        name: AR_EC_VF_nzoth_yogg_cthun_129962315593647_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYYAAAAAAAAAAAAAGmFzYmZ2GjZmZmtBGMbMzMGzGDMGDziZbqZGsgZAMzilpmFDAZMWA
      single:
        name: AR_SP_VF_cthun_80658376897455_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAAMmZAAAAAAAAAAAAAGmFPwYmZ2GjZmZGzgBzGzMjxsxAjxwsY2mamBLwAYmNLTNLGAyYsA
      2t:
        name: AR_SP_VF_nzoth_yogg_cthun_129962386888623_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYMDAAAAAAAAAAAAwwsYGzMzGPgZmZmtBGMbMzMGzGDMGDziZbqZGsgZAMzmlpmFDAZMWA
      3t:
        name: AR_SP_VF_nzoth_yogg_cthun_129962283079599_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYYAAAAAAAAAAAAAGzsYGzMzGPgZmZmtBGMbMzMGzGDMGDziZbqZGsgZAMzmlpmFDAZMWA
      4t:
        name: AR_SP_VF_nzoth_yogg_cthun_129962283079599_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYYAAAAAAAAAAAAAGzsYGzMzGPgZmZmtBGMbMzMGzGDMGDziZbqZGsgZAMzmlpmFDAZMWA
  vw-da-cthun-me:
    gearSetup: default
    talents:
      composite:
        name: VW_DH_VW_DA_yshaarj_cthun_81150817859503_Spike_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYGPAAAAAAAAAAAAAwMsMGzMzyYMzMmtZwgZhZmxY2YgxYYWMbTNzgFYmZGAUAmtZbJY2YD
      dungeons:
        name: VW_DH_VW_DA_nzoth_cthun_98245820544943_Spike_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMwMzAAAAAAAAAAAAAwYs4BGzMzy4BMzMmtZwgZhZmxY2YgxYYWMbTNzgFYmZGAUAmtZbJY2YD
      single:
        name: VW_DH_VW_DA_yshaarj_cthun_81151053755311_Spike_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwwYAAAAAAAAAAAAAmZsMGzMzy4BMzMGzgBzCzMjxsxAjxwsY2mamBLwMzMAoAMbz2SwsxG
      2t:
        name: VW_DH_VW_DA_yshaarj_cthun_81150844065711_Spike_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYGAAAAAAAAAAAAAmZsMGzMzCjZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      3t:
        name: VW_DH_VW_DA_nzoth_cthun_98193274296239_Spike_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMwYGAAAAAAAAAAAAAmZsMGzMzCjZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      4t:
        name: VW_DH_DoS_DA_nzoth_cthun_98245891561391_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZmHAAAAAAAAAAAAAwYmFPwYmZWYMzMmtZwgZhZmxY2YgxYYWMbTNzgFYMzAgCwsNbLBzGL
  vw-vf-cthun:
    gearSetup: default
    talents:
      composite:
        name: VW_DH_VW_VF_yshaarj_cthun_81151155492783_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYmZAAAAAAAAAAAAAmhtxYmZ2gZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      dungeons:
        name: VW_DH_VW_VF_nzoth_cthun_98245887645615_Spike_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMwMzAAAAAAAAAAAAAwYs4BGzMzGjZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      single:
        name: VW_VE_VW_VF_yshaarj_cthun_81151120585647_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYAGDAAAAAAAAAAAAwMzsMGzMz2YMzMGzgBzCzMjxsxAjxwsY2mamBLwYmBAFgZbWWCmN2A
      2t:
        name: VW_DH_VW_VF_yshaarj_cthun_81151155492783_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYmZAAAAAAAAAAAAAmhtxYmZ2gZmxsNDGMLMzMGzGDMGDziZbqZGsAzMzAgCwsNbLBzGb
      3t:
        name: VW_VE_VW_VF_nzoth_cthun_98246130636719_Flay_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZGDAAAAAAAAAAAAw4BmNPwYmZ2YMzMmtZwgZhZmxY2YgxYYWMbTNzgFYMzAgCwsNLLBzGb
      4t:
        name: VW_DH_VW_VF_nzoth_cthun_98245891561391_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZmHAAAAAAAAAAAAAwYmFPwYmZ2YMzMmtZwgZhZmxY2YgxYYWMbTNzgFYMzAgCwsNbLBzGb
gear:
  # 12.8k Mastery (13%) | 13.3k Haste (20%) | 8.2k Crit (17%) | 500 Vers (1%)
  default:
    head: "living_lusters_semblance,id=212083,ilevel=632" # mastery/crit
    neck: "sureki_zealots_insignia,id=225577,ilevel=636" # haste/mastery
    shoulders: "living_lusters_dominion,id=212081,ilevel=632" # haste/vers
    back: "wings_of_shattered_sorrow,id=225574,ilevel=636" # crit/haste
    chest: "living_lusters_raiment,id=212086,ilevel=632" # haste/mastery
    wrists: "skeinspinners_duplicitous_cuffs,id=225584,ilevel=636" # haste/mastery
    hands: "punctured_apiary_gloves,id=221067,ilevel=632" # haste/mastery
    waist: "acrid_ascendants_sash,id=225585,ilevel=636" # mastery/haste
    legs: "living_lusters_trousers,id=212082,ilevel=636" # mastery/crit
    feet: "assimilated_eggshell_slippers,id=225582,ilevel=632" # mastery/haste
    finger1: "writhing_ringworm,id=225576,ilevel=632" # mastery/haste
    finger2: "seal_of_the_poisoned_pact,id=225578,ilevel=632" # crit/mastery
    trinket1: "unbound_changeling,id=178708,ilevel=632"
    trinket2: "signet_of_the_priory,id=219308,ilevel=632"
    main_hand: "takazjs_entropic_edict,id=212397,ilevel=636" # mastery/haste
    off_hand: ""
  # TODO: fix this
  # 12.8k Mastery (13%) | 13.3k Haste (20%) | 8.2k Crit (17%) | 500 Vers (1%)
  noCantrip:
    head: "living_lusters_semblance,id=212083,ilevel=632" # mastery/crit
    neck: "sureki_zealots_insignia,id=225577,ilevel=636" # haste/mastery
    shoulders: "living_lusters_dominion,id=212081,ilevel=632" # haste/vers
    back: "wings_of_shattered_sorrow,id=225574,ilevel=636" # crit/haste
    chest: "living_lusters_raiment,id=212086,ilevel=632" # haste/mastery
    wrists: "skeinspinners_duplicitous_cuffs,id=225584,ilevel=636" # haste/mastery
    hands: "punctured_apiary_gloves,id=221067,ilevel=632" # haste/mastery
    waist: "acrid_ascendants_sash,id=225585,ilevel=636" # mastery/haste
    legs: "living_lusters_trousers,id=212082,ilevel=636" # mastery/crit
    feet: "assimilated_eggshell_slippers,id=225582,ilevel=632" # mastery/haste
    finger1: "writhing_ringworm,id=225576,ilevel=632" # mastery/haste
    finger2: "seal_of_the_poisoned_pact,id=225578,ilevel=632" # crit/mastery
    trinket1: "unbound_changeling,id=178708,ilevel=632"
    trinket2: "signet_of_the_priory,id=219308,ilevel=632"
    main_hand: "takazjs_entropic_edict,id=212397,ilevel=636" # mastery/haste
    off_hand: ""
# TODO: support multi-colors here for the meta gem
gems:
  meta: "213743" # Culminating Blasphemite
  main: "213494" # Quick Onyx
enchants:
  head: ""
  chest: "councils_intellect_3"
  ring: "cursed_mastery_3"
  legs: "sunset_spellthread_3"
  main_hand: "authority_of_radiant_power_3"
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
  talents-top:
    description: "Shows top talents."
    iterations: 20000
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: "Combines the top trinkets together to get your BiS 2 trinkets.\n\nWIIF = Full, WIID = DPS only, WIIT = DPS + Tank, WIIH = DPS + Healer.\n\nOCEBA = Bronze, OCEEA = Emerald, OCEOA = Obsidian, OCEAA = Azure, OCERA = Ruby"
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 593
      - 606
      - 619
      - 626
      - 629
      - 639
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsFatedRaids
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
threeTargetWeights: weightsThreeTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
dungeonSeason: 4
dungeonStandardWeights: weightsStandardSeasonFour
dungeonPushWeights: weightsPushSeasonFour
dungeonType: slice
simcBuild: latest
forceHeroTalents: false
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 100
  retryInterval: 10
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 4000
  steps: 1000
  total: 34000
  min:
    haste: 7000
    mastery: 7000
    crit: 3000
    vers: 0
  include:
    - mastery
    - haste
    - crit
    - versatility
