builds:
  # add here as well if you ever change this https://github.com/Bloodmallet/bloodytools/blob/master/bloodytools/simulations/talent_tree_paths/priest_shadow.yaml
  vw-cthun:
    gearSetup: default
    talents:
      composite:
        name: VW_VE_VW_DA_yshaarj_cthun_81151086016431_Flay_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYAzYAAAAAAAAAAAAAmxsNGzMzyYMzMmtZmZZwsxMzMjZjBGjhZxsN1MDWgxMDAEgZbWWCmN2A
      dungeons:
        name: VW_VE_DoS_DA_nzoth_cthun_98245887375279_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZGAAAAAAAAAAAAAGzs4BGzMzyYMzMmtZmZZwsxMzMjZjBGjhZxsN1MDWgxMDAEgZbWWCmNWA
      single:
        name: VW_VE_VW_DA_yshaarj_cthun_81151120585647_Flay_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYAGDAAAAAAAAAAAAwMzsNGzMzyYMzMGzMzygZjZmZGzGDMGDziZbqZGsAjZGAIAz2ssEMbsB
      2t:
        name: VW_DH_VW_DA_yshaarj_cthun_81151019186095_Spike_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAYwYGDAAAAAAAAAAAAwMsNGzMzy4BMzMmtZmZZwsxMzMjZjBGjhZxsN1MDWgZmZAgAMbz2SwsxG
      4t:
        name: VW_VE_DoS_DA_nzoth_cthun_98245887375279_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZGAAAAAAAAAAAAAGzs4BGzMzyYMzMmtZmZZwsxMzMjZjBGjhZxsN1MDWgxMDAEgZbWWCmNWA
      8t:
        name: VW_DH_DoS_VF_nzoth_cthun_98245891561391_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZmHAAAAAAAAAAAAAwYmFPwYmZ2YMzMmtZmZZwsxMzMjZjBGjhZxsN1MDWgxMDAEgZb2WCmNWA
  ar-vf-cthun-flay-me:
    gearSetup: default
    talents:
      composite:
        name: AR_SP_VF_cthun_80588449494959_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAAYmHYAAAAAAAAAAAAAGmlxYmZ2GjZmZmtZmZZwsxMzMjZjBGjhZxsN1MDWgBwMbWGNLGAyYsA
      dungeons:
        name: AR_EC_VF_nzoth_cthun_100436424505263_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMgZmBAAAAAAAAAAAAwwsYGzY2GjZmxsNzMLDmNmZmZMbMwYMMLmtpmZwCMAmZxyoZxAQGjFA
      single:
        name: AR_SP_VF_cthun_80658376897455_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAAMmZAAAAAAAAAAAAAGmFPwYmZ2GjZmZGzMzygZjZmZGzGDMGDziZbqZGsADgZ2sMaWMAkxYB
      2t:
        name: AR_SP_VF_nzoth_cthun_98240657044399_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMAmBAAAAAAAAAAAAwYml5BGzY2GjZmZGzMzygZjZmZGzGDMGDziZbqZGsADgZ2sMa2MAkxYB
      4t:
        name: AR_SP_VF_nzoth_cthun_99313291605935_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMAzMAAAAAAAAAAAAAGPwsYGzMz2YMzMzsNmZZwsxMzMjZjBGjhZxsN1MDWgBwMbWGNLGAyYsA
      8t:
        name: AR_EC_VF_nzoth_cthun_99313190942639_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMAz8AAAAAAAAAAAAAAGzsYGzMz2YMzMzsNmZZwsxMzMjZjBGjhZxsN1MDWgBwMLWGNLGAyYsA
  ar-vf-yogg-cthun-me:
    gearSetup: default
    talents:
      composite:
        name: AR_SP_VF_yogg_cthun_119173361940399_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAgBz8ADAAAAAAAAAAAAwwswYmZ2GjZmZmtxMLDmNmZmZMbMwYMMLmtpmZwCmBwMbWGNbGAyYsA
      dungeons:
        name: AR_EC_VF_nzoth_yogg_cthun_129962177181615_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYMAAAAAAAAAAAAAGmFzYmZ2GjZmZmtxMLDmNmZmZMbMwYMMLmtpmZwCmBwMLWGNLGAyYsA
      single:
        name: AR_SP_VF_yogg_cthun_119242215601071_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAgBmZAAAAAAAAAAAAAGmFPwYmZ2GjZmZGjZWGMbMzMzY2YgxYYWMbTNzgFMDgZ2sMaWMAkxYB
      2t:
        name: AR_SP_VF_yogg_cthun_121432648922031_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAgBmZAAAAAAAAAAAAAGmFzYGz2YMzMzYMzygZjZmZGzGDMGDziZbqZGsgZAMzmlRzmBgMGLA
      4t:
        name: AR_SP_VF_nzoth_yogg_cthun_129962177181615_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYMAAAAAAAAAAAAAGmFzYmZ2GjZmZmtxMLDmNmZmZMbMwYMMLmtpmZwCmBwMbWGNLGAyYsA
      8t:
        name: AR_EC_VF_nzoth_yogg_cthun_139024021305263_Flay_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMYmBAAAAAAAAAAAAwwsYGDz2YMzMzsNmZZwsxMzMjZjBGjhZxsN1MDWwMAmZxyoZxAQGjFA
hero:
  AR:
    AR_EC: "energy_compression:1/power_surge:1/perfected_form:1/resonant_energy:1/manifested_power:1/word_of_supremacy:1/incessant_screams:1/word_of_supremacy:1/empowered_surges:1/concentrated_infusion:1/energy_cycle:1/divine_halo:1"
    AR_SP: "sustained_potency:1/power_surge:1/perfected_form:1/resonant_energy:1/manifested_power:1/word_of_supremacy:1/incessant_screams:1/word_of_supremacy:1/empowered_surges:1/concentrated_infusion:1/energy_cycle:1/divine_halo:1"
  # Darkening Horizon is currently bugged, need to hard code 125982 for the ID
  VW:
    VW_VE_DoS: "void_empowerment:1/depth_of_shadows:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
    VW_DH_DoS: "125982:1/depth_of_shadows:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
    VW_VE_VW: "void_empowerment:1/voidwraith:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
    VW_DH_VW: "125982:1/voidwraith:1/entropic_rift:1/dark_energy:1/void_blast:1/inner_quietus:1/devour_matter:1/voidheart:1/void_infusion:1/void_leech:1/collapsing_void:1"
gear:
  # 16.2k Mastery (15.6%) | 14.4k Haste (21.8%) | 9k Crit (17.9%) | 652 Vers (0.8%)
  default:
    head: "living_lusters_semblance,id=212083,ilevel=639" # mastery/crit
    neck: "sureki_zealots_insignia,id=225577,ilevel=639" # haste/mastery
    shoulders: "living_lusters_dominion,id=212081,ilevel=639" # haste/vers
    back: "wings_of_shattered_sorrow,id=225574,ilevel=639" # crit/haste
    chest: "living_lusters_raiment,id=212086,ilevel=639" # haste/mastery
    wrists: "consecrated_cuffs,id=222815,bonus_id=8793/11109,ilevel=636" # haste/mastery
    hands: "gory_surgeons_gloves,id=178748,ilevel=639" # mastery/crit
    waist: "acrid_ascendants_sash,id=225585,ilevel=639" # mastery/haste
    legs: "living_lusters_trousers,id=212082,ilevel=639" # crit/haste
    feet: "assimilated_eggshell_slippers,id=225582,ilevel=639" # mastery/haste
    finger1: "writhing_ringworm,id=225576,ilevel=639" # mastery/haste
    finger2: "seal_of_the_poisoned_pact,id=225578,ilevel=639" # crit/mastery
    trinket1: "spymasters_web,id=220202,ilevel=639"
    trinket2: "arakara_sacbrood,id=219314,ilevel=639"
    main_hand: "wand_of_untainted_power,id=133288,ilevel=639" # haste/mastery
    off_hand: "vagabonds_torch,id=222566,ilevel=636,bonus_id=11300/8793" # haste/mastery
  # 22.8k Mastery (20%) | 11.1k Haste (17%) | 5.5k Crit (13%) | 700 Vers (1%)
  noCantrip:
    head: "living_lusters_semblance,id=212083,ilevel=639" # mastery/crit
    neck: "emergency_stop_keychain,id=221077,ilevel=639" # mastery/haste
    shoulders: "living_lusters_dominion,id=212081,ilevel=639" # haste/vers
    back: "wings_of_shattered_sorrow,id=225574,ilevel=639" # crit/haste
    chest: "living_lusters_raiment,id=212086,ilevel=639" # haste/mastery
    wrists: "skeinspinners_duplicitous_cuffs,id=225584,ilevel=639" # haste/mastery
    hands: "gory_surgeons_gloves,id=178748,ilevel=639" # haste/mastery
    waist: "acrid_ascendants_sash,id=225585,ilevel=639" # mastery/haste
    legs: "living_lusters_trousers,id=212082,ilevel=639" # crit/haste
    feet: "assimilated_eggshell_slippers,id=225582,ilevel=639" # mastery/haste
    finger1: "writhing_ringworm,id=225576,ilevel=639" # mastery/haste
    finger2: "umbriss_band,id=133286,ilevel=639" # mastery/crit
    trinket1: "spymasters_web,id=220202,ilevel=639" # mastery
    trinket2: "arakara_sacbrood,id=219314,ilevel=639" # haste
    main_hand: "takazjs_entropic_edict,id=212397,ilevel=639" # mastery/haste
    off_hand: ""
gems:
  meta: "213743" # Culminating Blasphemite
  main: "213494" # Quick Onyx
  emerald: "213482" # Masterful Emerald
  ruby: "213458" # Masterful Ruby
  onyx: "213497" # Masterful Onyx
  sapphire: "213470" # Quick Sapphire
  amber: "213506" # Quick Amber
enchants:
  head: ""
  chest: "crystalline_radiance_3"
  ring: "radiant_mastery_3"
  legs: "sunset_spellthread_3"
  main_hand: "authority_of_the_depths_3"
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gem-combos:
    description: "Sims combinations of gems to optimize the meta gems using 1 of each color. Only uses max rank of gems"
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 1000 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
  talents-top:
    description: "Shows top talents."
    iterations: 20000
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: "Combines the top trinkets together to get your BiS 2 trinkets."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 593
      - 606
      - 619
      - 626
      - 629
      - 639
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsNerubarPalace
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
threeTargetWeights: weightsThreeTargets
fourTargetWeights: weightsFourTargets
eightTargetWeights: weightsEightTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
dungeonSeason: 1
dungeonStandardWeights: weightsSeasonOne
dungeonPushWeights: weightsSeasonOne
dungeonType: route
simcBuild: latest
forceHeroTalents: false
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 100
  retryInterval: 10
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 4000
  steps: 1000
  total: 37000
  min:
    haste: 8000
    mastery: 10000
    crit: 3000
    vers: 0
  include:
    - mastery
    - haste
    - crit
    - versatility
